"""EmployeeManagementSystem URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

from EMS import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('adminDashboard/newAdmin/', views.newAdmin, name="newAdmin"),
    path('saveAdmin/', views.saveAdmin),
    path('adminDashboard/adminDetails/', views.adminDetails, name="adminDetails"),
    path('adminDashboard/index/', views.adminIndexPage, name="adminDashboard"),
    path('adminDashboard/base', views.base, name="adminBase"),
    path('adminDashboard/employeeRequest', views.employeeRequest, name="employeeRequest"),
    path('adminDashboard/managerRequest', views.managerRequest, name="managerRequest"),
    path('adminDashboard/clientRequest', views.clientRequest, name="clientRequest"),
    path('adminDashboard/projectRequest', views.projectRequest, name="projectRequest"),
    path('adminDashboard/projectView/<int:pk>', views.projectView, name="projectView"),
    path('adminDashboard/allProject', views.allProject, name="allProject"),
    path('adminDashboard/allManager', views.allManager, name="allManager"),
    path('adminDashboard/allEmployee', views.allEmployee, name="allEmployee"),
    path('adminDashboard/allClient', views.allClient, name="allClient"),
    path('adminDashboard/employeeProfile/<str:pk>', views.employeeProfile, name="employeeProfile"),
    path('adminDashboard/managerProfile/<str:pk>', views.managerProfile, name="managerProfile"),
    path('adminDashboard/clientProfile/<int:pk>', views.clientProfile, name="clientProfile"),
    path('adminDashboard/editEmployee/<str:pk>', views.editEmployee, name="editEmployee"),
    path('editManager/<str:pk>', views.editManager, name="editManager"),
    path('editClient/<int:pk>', views.editClient, name="editClient"),
    path('updateEmployee/', views.updateEmployee),
    path('updateManager/', views.updateManager),
    path('updateClient/',views.updateClient),
    path('deleteEmployee/<str:pk>', views.deleteEmployee, name="deleteEmployee"),
    path('deleteManager/<str:pk>', views.deleteManager, name="deleteManager"),
    path('adminDashboard/managerRequestView/<str:pk>', views.managerRequestView, name="managerRequestView"),
    path('adminDashboard/employeeRequestView/<str:pk>', views.employeeRequestView, name="employeeRequestView"),
    path('adminDashboard/clientRequestView/<int:pk>', views.clientRequestView, name="clientRequestView"),
    path('assignManager/', views.assignManager),
    path('managerRequestEdit/', views.managerRequestEdit),
    path('assignManagerClient/', views.assignManagerClient),
    path('adminDashboard/hoildays', views.hoildays, name="hoildays"),
    path('saveHoilday/', views.saveHoilday),
    path('adminDashboard/employeeStatus', views.employeeStatus, name="employeeStatus"),
    path('adminDashboard/showStatus<str:pk>', views.showStatus, name="showStatus"),
    path('adminDashboard/filterEmployee', views.filterEmployee, name="filterEmployee"),
    path('savefilterEmployee/', views.savefilterEmployee),
    path('adminDashboard/attendance', views.attendance, name="attendance"),
    path('adminDashboard/attendanceFilter', views.attendanceFilter, name="attendanceFilter"),
    path('adminDashboard/salary', views.salary, name="salary"),
    path('adminDashboard/salaryView', views.salaryView, name="salaryView"),
    path('genrateSalary/<str:pk>', views.genrateSalary, name="genrateSalary"),
    path('adminDashboard/leave', views.adminLeave, name="adminLeave"),
    path('adminDashboard/notice', views.notice, name="notice"),
    path('saveNotice/', views.saveNotice),
    path('adminDashboard/reportEmployee', views.reportEmployee, name="reportEmployee"),
    path('adminDashboard/reportManager', views.reportManager, name="reportManager"),
    path('adminDashboard/reportClient', views.reportClient, name="reportClient"),
    path('adminDashboard/reportEmployeeFilter', views.reportEmployeeFilter, name="reportEmployeeFilter"),
    path('searchReportEmployeeFilter/', views.searchReportEmployeeFilter),
    path('adminDashboard/reportProject', views.reportProject, name="reportProject"),
    path('searchReportProjectFilter/', views.searchReportProjectFilter),
    path('adminDashboard/projectProgressAdmin/<int:pk>', views.projectProgressAdmin, name="projectProgressAdmin"),

    path('clientDashboard/base/', views.Cbase, name="base"),
    path('clientDashboard/index/', views.clientIndexPage, name="clientDashboard"),
    path('clientDashboard/addProject', views.addProject, name="addProject"),
    path('saveProject/', views.saveProject, name="saveProject"),
    path('clientDashboard/profile', views.profileClient, name="profileClient"),
    path('saveProfileClient/', views.saveProfileClient),
    path('clientDashboard/projects',views.projectClient, name="projectClient"),
    path('clientDashboard/projectProgress/<int:pk>', views.projectProgress, name="projectProgress"),
    path('clientDashboard/changePassword', views.clientChangePassword, name="clientChangePassword"),

    path('employeeDashboard/index/', views.employeeIndexPage, name="employeeDashboard"),
    path('employeeDashboard/base', views.Ebase, name="employeeBase"),
    path('employeeDashboard/leave', views.employeeLeave, name="employeeLeave"),
    path('saveLeave/', views.saveLeave),
    path('employeeDashboard/leaveStatus', views.leaveStatus, name="leaveStatus"),
    path('searchLeaveStatus/', views.searchLeaveStatus),
    path('employeeDashboard/workUpload', views.workUpload, name="workUpload"),
    path('saveWorkDone/', views.saveWorkDone),
    path('employeeDashboard/userProfile', views.userProfile, name="userProfile"),
    path('saveUserProfile/', views.saveUserProfile),
    path('employeeDashboard/projects', views.projectEmployee, name="projectEmployee"),
    path('employeeDashboard/projectView/<int:pk>', views.employeeProjectView, name="employeeProjectView"),
    path('employeeDashboard/changePassword', views.changePassword, name="changePassword"),
    path('changePasswordEmployee/', views.changePasswordEmployee),
    path('employeeDashboard/tasksDetails', views.tasksDetails, name="tasksDetails"),
    path('employeeDashboard/paySlip', views.paySlip, name="paySlip"),
    path('searchPaySlip/', views.searchPaySlip),
    path('employeeDashboard/salaryPrint/<str:pk>', views.salaryPrint, name="salaryPrint"),
    path('employeeDashboard/hoildays', views.employeeHolidays, name="employeeHolidays"),

    path('managerDashboard/index/', views.managerIndexPage, name="managerDashboard"),
    path('managerDashboard/base', views.Mbase, name="managerBase"),
    path('managerDashboard/teamMembers', views.managerTeam, name="teamMembers"),
    path('managerDashboard/leaveRequest', views.leaveRequest, name="leaveRequest"),
    path('managerDashboard/leaveAccepted', views.leaveAccepted, name="leaveAccepted"),
    path('managerDashboard/leaveRejected', views.leaveRejected, name="leaveRejected"),
    path('managerDashboard/editLeave<int:pk>', views.editLeave, name="editLeave"),
    path('saveEditLeave/', views.saveEditLeave),
    path('managerDashboard/employeeWorkStatus', views.employeeWorkStatus, name="employeeWorkStatus"),
    path('saveEmployeeWorkStatus/', views.saveEmployeeWorkStatus),
    path('managerDashboard/profile', views.profileManager, name="profileManager"),
    path('saveProfile/', views.saveProfile),
    path('managerDashboard/projects', views.projects, name="projects"),
    path('managerDashboard/changePassword', views.PasswordManager, name="changePasswordManager"),
    path('changePasswordManager/', views.changePasswordManager),
    path('managerDashboard/projectDetails', views.projectDetails, name="projectDetails"),
    path('managerDashboard/addTasks', views.addTasks, name="addTasks"),
    path('saveAddTasks/',views.saveAddTasks),
    path('managerDashboard/viewTasks', views.viewTasks,name="viewTasks"),
    path('managerDashboard/teamAttendance', views.teamAttendance, name='teamAttendance'),
    path('managerDashboard/projectView/<int:pk>', views.managerProjectView, name="managerProjectView"),
    path('managerDashboard/viewEmployee/<str:pk>', views.viewEmployee, name="viewEmployee"),
    path('managerDashboard/hoildays', views.managerHolidays, name="managerHolidays"),
    path('projectStatusChange/', views.projectStatusChange),


    path('managerRegistration', views.managerRegistration, name="managerRegistration"),
    path('saveManager/', views.saveManager),
    path('managerLogin/', views.managerLogin, name="managerLogin"),
    path('loginManager/', views.loginManager, name="loginManager"),
    path('employeeRegistration', views.employeeRegistration, name="employeeRegistration"),
    path('saveEmployee/', views.saveEmployee),
    path('employeeLogin/', views.employeeLogin, name="employeeLogin"),
    path('loginEmployee/', views.loginEmployee, name="loginEmployee"),
    path('clientRegistration', views.clientRegistration, name="clientRegistration"),
    path('saveClient/', views.saveClient),
    path('clientLogin/', views.clientLogin, name="clientLogin"),
    path('loginClient/', views.loginClient, name="loginClient"),
    path('aboutUs/', views.aboutUs, name="aboutUs"),
    path('adminLogin/', views.adminlogin, name="adminlogin"),
    path('loginAdmin/', views.loginAdmin, name="loginAdmin"),
    path('logOut', views.logOut, name="logOut"),
    path('logOutManager', views.logOutManager, name="logOutManager"),
    path('logOutClient', views.logOutClient, name="logOutClient"),
    path('m1<str:pk>/', views.m1, name="m1"),
    path('jobList/', views.jobList, name="jobList"),
    path('jobDetails/', views.jobDetails, name="jobDetails"),
    path('jobDetailsManager/', views.jobDetailsManager, name="jobDetailsManager"),
]
