# Generated by Django 3.1.7 on 2021-03-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('bloodGroup', models.CharField(max_length=20)),
                ('joinDate', models.DateField(null=True)),
                ('salary', models.IntegerField(null=True)),
                ('leave', models.IntegerField(null=True)),
                ('qualification', models.CharField(max_length=30)),
                ('activation_Date', models.DateTimeField(null=True)),
                ('deactivation_Date', models.DateTimeField(null=True)),
                ('account', models.CharField(default='Deactive', max_length=20)),
                ('emailId', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('managerCode', models.CharField(default='None', editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('resume', models.FileField(upload_to='documents')),
            ],
        ),
    ]
