# Generated by Django 3.1.7 on 2021-03-22 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0003_auto_20210320_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('clientId', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('companyName', models.CharField(max_length=40)),
                ('companyAddress', models.CharField(max_length=40)),
                ('companyState', models.CharField(max_length=20)),
                ('emailId', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('companyDescription', models.CharField(max_length=40)),
                ('registration_Date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('activation_Date', models.DateTimeField(null=True)),
                ('deactivation_Date', models.DateTimeField(null=True)),
                ('account', models.CharField(default='Deactive', max_length=20)),
            ],
        ),
    ]
