# Generated by Django 3.1.7 on 2021-03-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0004_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('hoildayId', models.IntegerField(primary_key=True, serialize=False)),
                ('holidayName', models.CharField(max_length=20)),
                ('hoildayDescription', models.CharField(max_length=30)),
                ('hoildayDate', models.DateField()),
                ('hoildayDay', models.CharField(max_length=20)),
            ],
        ),
    ]
