# Generated by Django 3.1.7 on 2021-03-23 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0005_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientProject',
            fields=[
                ('projectId', models.IntegerField(primary_key=True, serialize=False)),
                ('clientId', models.IntegerField()),
                ('managerId', models.IntegerField()),
                ('projectName', models.CharField(max_length=20, null=True)),
                ('projectDescription', models.CharField(max_length=60)),
                ('totalDays', models.IntegerField()),
                ('otherDays', models.IntegerField(null=True)),
                ('createdDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
