# Generated by Django 3.1.7 on 2021-03-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0006_clientproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='managerId',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
