# Generated by Django 3.1.7 on 2021-03-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0007_auto_20210325_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='managerId',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
