# Generated by Django 3.1.7 on 2021-03-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0009_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='leave',
            field=models.IntegerField(default=14, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=30000, null=True),
        ),
    ]
