# Generated by Django 3.1.7 on 2021-03-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0010_auto_20210326_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='managerId',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='managerName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
