# Generated by Django 3.1.7 on 2021-03-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0011_auto_20210330_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='leave',
            field=models.IntegerField(default=14, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='salary',
            field=models.IntegerField(default=30000, null=True),
        ),
    ]
