# Generated by Django 3.1.7 on 2021-04-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0014_leave_totaldays'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeDailyWork',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=20)),
                ('managerId', models.CharField(max_length=20)),
                ('clientId', models.IntegerField()),
                ('workDescription', models.CharField(max_length=40)),
                ('loginTime', models.DateTimeField()),
                ('logoutTime', models.DateTimeField()),
            ],
        ),
    ]
