# Generated by Django 3.1.7 on 2021-04-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0017_auto_20210402_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedailywork',
            name='loginTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='employeedailywork',
            name='logoutTime',
            field=models.TimeField(null=True),
        ),
    ]
