# Generated by Django 3.1.7 on 2021-04-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0019_auto_20210410_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='projectId',
        ),
        migrations.AddField(
            model_name='tasks',
            name='employeeName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='projectName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
