# Generated by Django 3.1.7 on 2021-04-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0020_auto_20210411_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='perDaySalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empCode', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('totalTime', models.IntegerField()),
                ('daySalary', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='employeedailywork',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
