# Generated by Django 3.1.7 on 2021-04-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0021_auto_20210413_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedailywork',
            name='loginHour',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employeedailywork',
            name='loginTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeedailywork',
            name='logoutTime',
            field=models.DateTimeField(null=True),
        ),
    ]
