# Generated by Django 3.1.7 on 2021-04-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0026_auto_20210419_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthsalary',
            name='daySalary',
        ),
        migrations.AddField(
            model_name='clientproject',
            name='deadlineDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='leaveType',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='monthsalary',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
