# Generated by Django 3.1.7 on 2021-04-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0027_auto_20210421_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absentStatus',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='manager',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
