# Generated by Django 3.1.7 on 2021-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0028_auto_20210423_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='about',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
