# Generated by Django 3.1.7 on 2021-05-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0029_auto_20210423_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='employeeName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
