# Generated by Django 3.1.7 on 2021-05-13 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0032_employeedailywork_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('emailId', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('noticeDetails', models.CharField(max_length=100)),
                ('noticeDate', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
