# Generated by Django 3.1.7 on 2021-06-02 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0033_admin_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('noticeDetails', models.CharField(max_length=100)),
                ('noticeDate', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
